In [ ]:
'''Think of yourself, currently working as a Business analyst in one of the top sports company. The senior management team has asked you to come up with metrics with which they can gauge which team will win the upcoming La Liga cup (Football tournament).
The data set contains information on all the teams so far participated in all the past tournaments. It has data about how many goals each team scored, conceded, how many times they came within first 6 positions, how many seasons they have qualified, their best position in the past etc.
 
You are required to do the following:
1.	Read the data set and replace dashes with 0 to make sure you can perform arithmetic operations on the data. (2.5 points)
2.	Print all the teams which have started playing between 1930-1980. (5 points)
3.	Print the list of teams which came Top 5 in terms of points (2.5 points)
4.	Write a function with name “Goal_diff_count” which should return all the teams with their Goal Differences. Using the same function, find the team which has maximum and minimum goal difference. (5 points)
Goal_diff_count = GoalsFor - GoalsAgainst
 5. Create a new column with name “Winning Percent” and append it to the data set (5 points)
Percentage of Winning = (GamesWon / GamesPlayed)*100
If there are any numerical error, replace it with 0%
Print the top 5 teams which has the highest Winning percentage
 6. Group teams based on their “Best position” and print the sum of their points for all positions (5 points)
Eg: Best Position     Points 
         1                   25000
         2                    7000
         '''

In [34]:
# Load the necessary packages

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import operator

mydata = pd.read_csv('Laliga.csv')

In [35]:
#1.Read the data set 
mydata.head(n= 20)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
1,1,Real Madrid,86,4385,2762,1647,552,563,5947,3140,33,23,8,8,3,4,79,1929,1929,1
2,2,Barcelona,86,4262,2762,1581,573,608,5900,3114,25,25,12,12,4,6,83,1929,1929,1
3,3,Atletico Madrid,80,3442,2614,1241,598,775,4534,3309,10,8,16,9,7,6,56,1929,2002-03,1
4,4,Valencia,82,3386,2664,1187,616,861,4398,3469,6,6,10,11,10,7,50,1931-32,1987-88,1
5,5,Athletic Bilbao,86,3368,2762,1209,633,920,4631,3700,8,7,10,5,8,10,49,1929,1929,1
6,6,Sevilla,73,2819,2408,990,531,887,3680,3373,1,4,4,5,12,6,32,1934-35,2001-02,1
7,7,Espanyol,82,2792,2626,948,608,1070,3609,3889,-,-,4,5,2,5,16,1929,1994-95,3
8,8,Real Sociedad,70,2573,2302,864,577,861,3228,3230,2,3,2,5,4,3,19,1929,2010-11,1
9,9,Zaragoza,58,2109,1986,698,522,766,2683,2847,-,1,4,5,4,4,18,1939-40,2012-13,2
10,10,Real Betis,51,1884,1728,606,440,682,2159,2492,1,-,2,3,4,4,14,1932-33,2015-16,1
11,11,Deportivo La Coruna,45,1814,1530,563,392,575,2052,2188,1,5,4,1,-,1,12,1941-42,2014-15,1
12,12,Celta Vigo,51,1789,1698,586,389,723,2278,2624,-,-,-,2,4,5,11,1939-40,2012-13,4
13,13,Valladolid,42,1471,1466,463,384,619,1767,2180,-,-,-,1,1,1,3,1948-49,2013-14,4
14,14,Racing Santander,44,1416,1428,453,336,639,1843,2368,-,1,1,2,-,1,5,1929,2011-12,2
15,15,Sporting Gijon,43,1389,1458,471,358,629,1753,2152,-,1,1,2,2,1,7,1944-45,2015-16,2
16,16,Osasuna,37,1351,1318,426,327,565,1500,1834,-,-,-,2,2,2,6,1935-36,2016-17,4
17,17,Malaga,36,1314,1255,390,330,535,1421,1763,-,-,-,1,-,1,2,1949-50,2008-09,4
18,18,Oviedo,38,1174,1192,408,292,492,1642,1951,-,-,3,2,2,4,11,1933-34,2000-01,3
19,19,Mallorca,27,1148,988,333,256,399,1182,1371,-,-,2,-,2,1,5,1960-61,2012-13,3

In [36]:
#replace dashes with 0 
mydata = mydata.replace('-', 0)

In [38]:
#moving the Column as column decription
mydata.columns = mydata.iloc[0]
mydata = mydata[1:]

In [40]:
mydata.dropna(inplace = True)

In [41]:
mydata.head(20)

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
1,1,Real Madrid,86,4385,2762,1647,552,563,5947,3140,33,23,8,8,3,4,79,1929,1929,1
2,2,Barcelona,86,4262,2762,1581,573,608,5900,3114,25,25,12,12,4,6,83,1929,1929,1
3,3,Atletico Madrid,80,3442,2614,1241,598,775,4534,3309,10,8,16,9,7,6,56,1929,2002-03,1
4,4,Valencia,82,3386,2664,1187,616,861,4398,3469,6,6,10,11,10,7,50,1931-32,1987-88,1
5,5,Athletic Bilbao,86,3368,2762,1209,633,920,4631,3700,8,7,10,5,8,10,49,1929,1929,1
6,6,Sevilla,73,2819,2408,990,531,887,3680,3373,1,4,4,5,12,6,32,1934-35,2001-02,1
7,7,Espanyol,82,2792,2626,948,608,1070,3609,3889,0,0,4,5,2,5,16,1929,1994-95,3
8,8,Real Sociedad,70,2573,2302,864,577,861,3228,3230,2,3,2,5,4,3,19,1929,2010-11,1
9,9,Zaragoza,58,2109,1986,698,522,766,2683,2847,0,1,4,5,4,4,18,1939-40,2012-13,2
10,10,Real Betis,51,1884,1728,606,440,682,2159,2492,1,0,2,3,4,4,14,1932-33,2015-16,1
11,11,Deportivo La Coruna,45,1814,1530,563,392,575,2052,2188,1,5,4,1,0,1,12,1941-42,2014-15,1
12,12,Celta Vigo,51,1789,1698,586,389,723,2278,2624,0,0,0,2,4,5,11,1939-40,2012-13,4
13,13,Valladolid,42,1471,1466,463,384,619,1767,2180,0,0,0,1,1,1,3,1948-49,2013-14,4
14,14,Racing Santander,44,1416,1428,453,336,639,1843,2368,0,1,1,2,0,1,5,1929,2011-12,2
15,15,Sporting Gijon,43,1389,1458,471,358,629,1753,2152,0,1,1,2,2,1,7,1944-45,2015-16,2
16,16,Osasuna,37,1351,1318,426,327,565,1500,1834,0,0,0,2,2,2,6,1935-36,2016-17,4
17,17,Malaga,36,1314,1255,390,330,535,1421,1763,0,0,0,1,0,1,2,1949-50,2008-09,4
18,18,Oviedo,38,1174,1192,408,292,492,1642,1951,0,0,3,2,2,4,11,1933-34,2000-01,3
19,19,Mallorca,27,1148,988,333,256,399,1182,1371,0,0,2,0,2,1,5,1960-61,2012-13,3
20,20,Las Palmas,33,1020,1096,367,242,487,1347,1746,0,1,1,1,1,1,5,1951-52,2015-16,2

In [42]:
#converting to Int so Arthematic operations can be done

mydata['Points'] = mydata['Points'].astype(int)
mydata['Seasons'] = mydata['Seasons'].astype(int)
mydata['GamesPlayed'] = mydata['GamesPlayed'].astype(int)
mydata['GamesWon'] = mydata['GamesWon'].astype(int)
mydata['GamesDrawn'] = mydata['GamesDrawn'].astype(int)
mydata['GamesLost'] = mydata['GamesLost'].astype(int)
mydata['GoalsFor'] = mydata['GoalsFor'].astype(int)
mydata['GoalsAgainst'] = mydata['GoalsAgainst'].astype(int)
mydata['Champion'] = mydata['Champion'].astype(int)
mydata['Runner-up'] = mydata['Runner-up'].astype(int)
mydata['Third'] = mydata['Third'].astype(int)
mydata['Fourth'] = mydata['Fourth'].astype(int)
mydata['Fifth'] = mydata['Fifth'].astype(int)
mydata['Sixth'] = mydata['Sixth'].astype(int)
mydata['T'] = mydata['T'].astype(int)
mydata['BestPosition'] = mydata['BestPosition'].astype(int)


mydata.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 61 entries, 1 to 61
Data columns (total 20 columns):
Pos              61 non-null object
Team             61 non-null object
Seasons          61 non-null int64
Points           61 non-null int64
GamesPlayed      61 non-null int64
GamesWon         61 non-null int64
GamesDrawn       61 non-null int64
GamesLost        61 non-null int64
GoalsFor         61 non-null int64
GoalsAgainst     61 non-null int64
Champion         61 non-null int64
Runner-up        61 non-null int64
Third            61 non-null int64
Fourth           61 non-null int64
Fifth            61 non-null int64
Sixth            61 non-null int64
T                61 non-null int64
Debut            61 non-null object
Since/LastApp    61 non-null object
BestPosition     61 non-null int64
dtypes: int64(16), object(4)
memory usage: 10.0+ KB

In [43]:
# 2.	Print all the teams which have started playing between 1930-1980
mydata.head(20)

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
1,1,Real Madrid,86,4385,2762,1647,552,563,5947,3140,33,23,8,8,3,4,79,1929,1929,1
2,2,Barcelona,86,4262,2762,1581,573,608,5900,3114,25,25,12,12,4,6,83,1929,1929,1
3,3,Atletico Madrid,80,3442,2614,1241,598,775,4534,3309,10,8,16,9,7,6,56,1929,2002-03,1
4,4,Valencia,82,3386,2664,1187,616,861,4398,3469,6,6,10,11,10,7,50,1931-32,1987-88,1
5,5,Athletic Bilbao,86,3368,2762,1209,633,920,4631,3700,8,7,10,5,8,10,49,1929,1929,1
6,6,Sevilla,73,2819,2408,990,531,887,3680,3373,1,4,4,5,12,6,32,1934-35,2001-02,1
7,7,Espanyol,82,2792,2626,948,608,1070,3609,3889,0,0,4,5,2,5,16,1929,1994-95,3
8,8,Real Sociedad,70,2573,2302,864,577,861,3228,3230,2,3,2,5,4,3,19,1929,2010-11,1
9,9,Zaragoza,58,2109,1986,698,522,766,2683,2847,0,1,4,5,4,4,18,1939-40,2012-13,2
10,10,Real Betis,51,1884,1728,606,440,682,2159,2492,1,0,2,3,4,4,14,1932-33,2015-16,1
11,11,Deportivo La Coruna,45,1814,1530,563,392,575,2052,2188,1,5,4,1,0,1,12,1941-42,2014-15,1
12,12,Celta Vigo,51,1789,1698,586,389,723,2278,2624,0,0,0,2,4,5,11,1939-40,2012-13,4
13,13,Valladolid,42,1471,1466,463,384,619,1767,2180,0,0,0,1,1,1,3,1948-49,2013-14,4
14,14,Racing Santander,44,1416,1428,453,336,639,1843,2368,0,1,1,2,0,1,5,1929,2011-12,2
15,15,Sporting Gijon,43,1389,1458,471,358,629,1753,2152,0,1,1,2,2,1,7,1944-45,2015-16,2
16,16,Osasuna,37,1351,1318,426,327,565,1500,1834,0,0,0,2,2,2,6,1935-36,2016-17,4
17,17,Malaga,36,1314,1255,390,330,535,1421,1763,0,0,0,1,0,1,2,1949-50,2008-09,4
18,18,Oviedo,38,1174,1192,408,292,492,1642,1951,0,0,3,2,2,4,11,1933-34,2000-01,3
19,19,Mallorca,27,1148,988,333,256,399,1182,1371,0,0,2,0,2,1,5,1960-61,2012-13,3
20,20,Las Palmas,33,1020,1096,367,242,487,1347,1746,0,1,1,1,1,1,5,1951-52,2015-16,2

In [45]:
# new data frame with split value columns 
new = mydata["Debut"].str.split("-", n = 1, expand = True)

# making seperate first name column from new data frame 
mydata["Debut"]= new[0] 
    
# df display 
mydata.head(20)

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
1,1,Real Madrid,86,4385,2762,1647,552,563,5947,3140,33,23,8,8,3,4,79,1929,1929,1
2,2,Barcelona,86,4262,2762,1581,573,608,5900,3114,25,25,12,12,4,6,83,1929,1929,1
3,3,Atletico Madrid,80,3442,2614,1241,598,775,4534,3309,10,8,16,9,7,6,56,1929,2002-03,1
4,4,Valencia,82,3386,2664,1187,616,861,4398,3469,6,6,10,11,10,7,50,1931,1987-88,1
5,5,Athletic Bilbao,86,3368,2762,1209,633,920,4631,3700,8,7,10,5,8,10,49,1929,1929,1
6,6,Sevilla,73,2819,2408,990,531,887,3680,3373,1,4,4,5,12,6,32,1934,2001-02,1
7,7,Espanyol,82,2792,2626,948,608,1070,3609,3889,0,0,4,5,2,5,16,1929,1994-95,3
8,8,Real Sociedad,70,2573,2302,864,577,861,3228,3230,2,3,2,5,4,3,19,1929,2010-11,1
9,9,Zaragoza,58,2109,1986,698,522,766,2683,2847,0,1,4,5,4,4,18,1939,2012-13,2
10,10,Real Betis,51,1884,1728,606,440,682,2159,2492,1,0,2,3,4,4,14,1932,2015-16,1
11,11,Deportivo La Coruna,45,1814,1530,563,392,575,2052,2188,1,5,4,1,0,1,12,1941,2014-15,1
12,12,Celta Vigo,51,1789,1698,586,389,723,2278,2624,0,0,0,2,4,5,11,1939,2012-13,4
13,13,Valladolid,42,1471,1466,463,384,619,1767,2180,0,0,0,1,1,1,3,1948,2013-14,4
14,14,Racing Santander,44,1416,1428,453,336,639,1843,2368,0,1,1,2,0,1,5,1929,2011-12,2
15,15,Sporting Gijon,43,1389,1458,471,358,629,1753,2152,0,1,1,2,2,1,7,1944,2015-16,2
16,16,Osasuna,37,1351,1318,426,327,565,1500,1834,0,0,0,2,2,2,6,1935,2016-17,4
17,17,Malaga,36,1314,1255,390,330,535,1421,1763,0,0,0,1,0,1,2,1949,2008-09,4
18,18,Oviedo,38,1174,1192,408,292,492,1642,1951,0,0,3,2,2,4,11,1933,2000-01,3
19,19,Mallorca,27,1148,988,333,256,399,1182,1371,0,0,2,0,2,1,5,1960,2012-13,3
20,20,Las Palmas,33,1020,1096,367,242,487,1347,1746,0,1,1,1,1,1,5,1951,2015-16,2

In [46]:
mydata.loc[operator.and_(mydata['Debut'] >='1930', mydata['Debut'] <= '1980')]

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
4,4,Valencia,82,3386,2664,1187,616,861,4398,3469,6,6,10,11,10,7,50,1931,1987-88,1
6,6,Sevilla,73,2819,2408,990,531,887,3680,3373,1,4,4,5,12,6,32,1934,2001-02,1
9,9,Zaragoza,58,2109,1986,698,522,766,2683,2847,0,1,4,5,4,4,18,1939,2012-13,2
10,10,Real Betis,51,1884,1728,606,440,682,2159,2492,1,0,2,3,4,4,14,1932,2015-16,1
11,11,Deportivo La Coruna,45,1814,1530,563,392,575,2052,2188,1,5,4,1,0,1,12,1941,2014-15,1
12,12,Celta Vigo,51,1789,1698,586,389,723,2278,2624,0,0,0,2,4,5,11,1939,2012-13,4
13,13,Valladolid,42,1471,1466,463,384,619,1767,2180,0,0,0,1,1,1,3,1948,2013-14,4
15,15,Sporting Gijon,43,1389,1458,471,358,629,1753,2152,0,1,1,2,2,1,7,1944,2015-16,2
16,16,Osasuna,37,1351,1318,426,327,565,1500,1834,0,0,0,2,2,2,6,1935,2016-17,4
17,17,Malaga,36,1314,1255,390,330,535,1421,1763,0,0,0,1,0,1,2,1949,2008-09,4
18,18,Oviedo,38,1174,1192,408,292,492,1642,1951,0,0,3,2,2,4,11,1933,2000-01,3
19,19,Mallorca,27,1148,988,333,256,399,1182,1371,0,0,2,0,2,1,5,1960,2012-13,3
20,20,Las Palmas,33,1020,1096,367,242,487,1347,1746,0,1,1,1,1,1,5,1951,2015-16,2
22,22,Granada,23,667,742,218,175,349,819,1157,0,0,0,0,0,2,2,1941,2016-17,6
23,23,Rayo Vallecano,17,662,652,189,148,305,760,1088,0,0,0,0,0,0,0,1977,2015-16,8
24,24,Elche,21,606,678,203,180,295,750,1022,0,0,0,0,1,1,2,1959,2014-15,5
26,26,Hercules,20,538,628,184,149,295,716,1050,0,0,0,0,1,4,5,1935,2010-11,5
27,27,Tenerife,13,510,494,155,128,211,619,744,0,0,0,0,2,0,2,1961,2009-10,5
28,28,Murcia,18,445,586,145,143,298,607,992,0,0,0,0,0,0,0,1940,2007-08,11
29,29,Alaves,12,421,380,125,81,174,458,623,0,0,0,0,0,1,1,1930,2016-17,6
30,30,Levante,11,416,402,113,95,194,430,632,0,0,0,0,0,1,1,1963,2015-16,6
31,31,Salamanca,12,375,423,123,102,198,422,581,0,0,0,0,0,0,0,1974,1998-99,7
32,32,Sabadell,14,353,426,129,95,202,492,720,0,0,0,1,1,0,2,1943,1987-88,4
33,33,Cadiz,12,343,448,104,127,217,393,662,0,0,0,0,0,0,0,1977,2005-06,12
35,35,Castellon,11,285,334,103,79,152,419,588,0,0,0,1,2,0,3,1941,1990-91,4
38,38,Cordoba,9,230,282,82,63,137,285,430,0,0,0,0,1,0,1,1962,2014-15,5
40,40,Recreativo,5,188,186,50,46,90,202,296,0,0,0,0,0,0,0,1978,2008-09,8
41,41,Burgos CF,6,168,204,59,50,95,216,310,0,0,0,0,0,0,0,1971,1979-80,12
42,42,Pontevedra,6,150,180,53,44,83,165,221,0,0,0,0,0,0,0,1963,1969-70,7
47,47,Gimnastic,4,91,116,34,16,66,181,295,0,0,0,0,0,0,0,1947,2006-07,7
50,50,Alcoyano,4,76,108,30,16,62,145,252,0,0,0,0,0,0,0,1945,1950-51,10
51,51,Jaen,3,71,90,29,13,48,121,183,0,0,0,0,0,0,0,1953,1957-58,14
53,53,AD Almeria,2,52,68,17,18,33,71,116,0,0,0,0,0,0,0,1979,1980-81,10
55,55,Lleida,2,40,68,13,14,41,70,182,0,0,0,0,0,0,0,1950,1993-94,16
58,58,Condal,1,22,30,7,8,15,37,57,0,0,0,0,0,0,0,1956,1956-57,16
59,59,Atletico Tetuan,1,19,30,7,5,18,51,85,0,0,0,0,0,0,0,1951,1951-52,16
60,60,Cultural Leonesa,1,14,30,5,4,21,34,65,0,0,0,0,0,0,0,1955,1955-56,15

In [47]:
#3.	Print the list of teams which came Top 5 in terms of points 
sort_by_points = mydata.sort_values('Points',ascending = False)
sort_by_points.head()

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
1,1,Real Madrid,86,4385,2762,1647,552,563,5947,3140,33,23,8,8,3,4,79,1929,1929,1
2,2,Barcelona,86,4262,2762,1581,573,608,5900,3114,25,25,12,12,4,6,83,1929,1929,1
3,3,Atletico Madrid,80,3442,2614,1241,598,775,4534,3309,10,8,16,9,7,6,56,1929,2002-03,1
4,4,Valencia,82,3386,2664,1187,616,861,4398,3469,6,6,10,11,10,7,50,1931,1987-88,1
5,5,Athletic Bilbao,86,3368,2762,1209,633,920,4631,3700,8,7,10,5,8,10,49,1929,1929,1

In [14]:
''''4  Write a function with name “Goal_diff_count” which should return all the teams with their Goal Differences. 
Using the same function, find the team which has maximum and minimum goal difference. 
Goal_diff_count = GoalsFor - GoalsAgainst

SyntaxError: EOF while scanning triple-quoted string literal (<ipython-input-14-75f745463d6e>, line 3)

In [50]:
''''4  Write a function with name “Goal_diff_count” which should return all the teams with their Goal Differences. 
Using the same function, find the team which has maximum and minimum goal difference. 
Goal_diff_count = GoalsFor - GoalsAgainst'''''
def Goal_diff_count(a) : 
    mydataF = a
    mydataF["Goal_diff_count"] = mydataF["GoalsFor"] - mydataF["GoalsAgainst"]
    mydataF = mydataF.sort_values('Goal_diff_count',ascending = False)
    print("Team details with Max Goal diff is below ")
    print(mydataF.loc[1])
    print("                                 ")
    print("Team details with Min Goal diff is below")
    print(mydataF.loc[61])

Goal_diff_count(mydata)

Team details with Max Goal diff is below
0
Pos                          1
Team               Real Madrid
Seasons                     86
Points                    4385
GamesPlayed               2762
GamesWon                  1647
GamesDrawn                 552
GamesLost                  563
GoalsFor                  5947
GoalsAgainst              3140
Champion                    33
Runner-up                   23
Third                        8
Fourth                       8
Fifth                        3
Sixth                        4
T                           79
Debut                     1929
Since/LastApp             1929
BestPosition                 1
Goal_diff_count           2807
Name: 1, dtype: object

Team details with Min Goal diff is below
0
Pos                     61
Team                Girona
Seasons                  1
Points                   0
GamesPlayed              0
GamesWon                 0
GamesDrawn               0
GamesLost                0
GoalsFor                 0
GoalsAgainst             0
Champion                 0
Runner-up                0
Third                    0
Fourth                   0
Fifth                    0
Sixth                    0
T                        0
Debut                 2017
Since/LastApp      2017-18
BestPosition             9
Goal_diff_count          0
Name: 61, dtype: object

''' 5 - Create a new column with name “Winning Percent” and append it to the data set (5 points)
Percentage of Winning = (GamesWon / GamesPlayed)*100
If there are any numerical error, replace it with 0%
Print the top 5 teams which has the highest Winning percentage'''

In [51]:
mydata2 = mydata
mydata2["Winning Percent"] = ((mydata2["GamesWon"] / mydata2["GamesPlayed"])*100)
mydata2 = mydata2.sort_values('Winning Percent',ascending = False)
mydata2.head()

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,...,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition,Goal_diff_count,Winning Percent
1,1,Real Madrid,86,4385,2762,1647,552,563,5947,3140,...,8,8,3,4,79,1929,1929,1,2807,59.630702
2,2,Barcelona,86,4262,2762,1581,573,608,5900,3114,...,12,12,4,6,83,1929,1929,1,2786,57.241130
3,3,Atletico Madrid,80,3442,2614,1241,598,775,4534,3309,...,16,9,7,6,56,1929,2002-03,1,1225,47.475134
4,4,Valencia,82,3386,2664,1187,616,861,4398,3469,...,10,11,10,7,50,1931,1987-88,1,929,44.557057
5,5,Athletic Bilbao,86,3368,2762,1209,633,920,4631,3700,...,10,5,8,10,49,1929,1929,1,931,43.772629

In [ ]:
""""6. Group teams based on their “Best position” and print the sum of their points for all positions 
Eg: Best Position     Points 
         1                   25000
         2                    7000

In [52]:
#Groupby 
mydata.groupby('BestPosition')['Points'].sum()

BestPosition
1     27933
2      6904
3      5221
4      6563
5      1884
6      2113
7      1186
8      1134
9        96
10      450
11      445
12      511
14       71
15       14
16       81
17      266
19       81
20       34
Name: Points, dtype: int64